### ISSUE TITLE
Make shaderc dependency optional

### ISSUE THREAD

**Issue by codec-abc** [kas-gui/kas#123]
Hello!

We discussed a bit in [the 3D widget of Iced](https://github.com/hecrj/iced/issues/343) I started to experiment with KAS. So far I struggled a bit to compile it and run it because of the ``shaderc`` dependencies. As the Rust crate is a wrapper around a C++ lib, some C++ tools make it somewhat difficult to built. So far I run into these case:
* On Windows, when I try to build the KAS, ``shaderc`` wants ninja to build it. As I don't have it the build fail.
* On Linux, I tried to cross compile it to Windows using mingw. ``shaderc`` use C++ 11 and for some reason the mingw tools I have on Linux doesn't seem to support it. I did not dive into it so it may be a incorrect use of me.

Anyway, I find that the use of ``shaderc`` make the compilation harder. I tried to compile KAS without ``shaderc`` and it was very easy. Basically, what I did was compile the existing shaders to SPIR-V using this [online tool](https://alexaltea.github.io/glslang.js). I also edited the ShaderManager from 
````rust
let vert_3122 = compile!(device, Vertex, "shaders_bin/scaled3122.vert");
````

to

````rust
let vert_3122 = device.create_shader_module(wgpu::include_spirv!("shaders_spir-v/scaled3122.vert"))
````
and it just worked.

So, my point is that since ``shaderc`` make the compilation less reliable it could be made an optional feature. That way, people who are OK with compiling their shaders before compile time can do it easily don't have to deal with ``shaderc``. The other that want a shader compiler that can be used at runtime can enable the flag and use it as today.

What do you think?

**Comment by dhardy** [comment]
Thanks for taking a look into this. I agree, ahead-of-time compilation of shaders and distribution of SPIR-V would be a good way of solving this problem — ideally though I'd like to automate compilation in the build process, which still requires a build-dependency on a shader compiler. I'll see if I can find a way of doing this without making that a hard dependency.

**Comment by codec-abc** [comment]
I was able to build it on Windows. I will test to cross-compile it on Linux tomorrow. But since I get the branch the shade were already compiled so the ``glslc`` command was not executed (which is intended). But if I modify the a shader source then the build script try to compile the shaders to spir-v and the compilation fail (because I don't have ``glslc`` installed). So this is a bit weird from a user PoV, because if you happen to modify a shader then there is a fair chance that suddenly you are not able to compile KAS anymore and have to rely on some externals C++ code/tool.

**Comment by dhardy** [comment]
Yes. Perhaps it should stop with a better error message, and perhaps it should be configurable (I don't know what other shader compilers might be available). Unfortunately it's not so easy to determine whether `glslc` is available without trying to run it (examining the `PATH` env var would work, but may be a portability hazard). Catching the error might work.

But what is the alternative? Not recompiling shaders is also weird because it silently skips a required build step.

**Comment by codec-abc** [comment]
I feel there is no magic solution here. The best one would be to have a pure Rust GLSL -> SPIR-V compiler that way it can be used dynamically at run-time or at build time. Until then, I think having the less intrusive build would be the best option. I bet that people using KAS and modifying shaders would be a very small subset of KAS users and for them knowing to recompile manually their shaders each time would be acceptable. Plus each can scripts the compilation the way that suit them the most. Anyway, I still think the current solution is at least a nice progress. I can now build KAS and the final executable is smaller. So a big thanks for this.

**Comment by dhardy** [comment]
Yeah, I guess it makes sense if automatic compilation is opt-in. Maybe using an env var like `SHADERC=glslc`.
