### ISSUE TITLE
custom usage of MessageBox 

### ISSUE THREAD

**Issue by codec-abc** [kas-gui/kas#127]
Hi,

I am a bit struggling with a way to use a message box. What I want to achieve here is a custom message box that could used to edit a string value. In my case this is to bypass the limitation of the missing Open dialog. I copy pasted the default MessageBox and tweaked in to add the widget I need.

Here what it looks like:
![image](https://user-images.githubusercontent.com/1208646/95020882-15645c00-066e-11eb-96cf-8742ee4bfb24.png)

My question is how I can send back data from the messageBox to "its parent" (ie, the code which created it). Basically I want to send a message with the following enum
````rust
enum MessageBoxResult {
    Ok(String), // new path,
    Cancel,
}
````

Also, I noted that when clicking the quit button of the messagebox sometime it close the popup as expected and sometime the program stop with this

````
error: process didn't exit successfully: `target\debug\kas-ui.exe` (exit code: 0xc000041d)
````

At first glance, it does not seems deterministic. 

Do you have any idea what could happen here ?

**Comment by codec-abc** [comment]
For the record here is the call stack I get with Visual Studio:
![image](https://user-images.githubusercontent.com/1208646/95021199-d505dd80-066f-11eb-9c13-8e4fd8e1ce96.png)

**Comment by dhardy** [comment]
To be honest, data flow for child windows is something I haven't found a good solution to yet. It would be *nice* to be able to do something like this:
```rust
let result = mgr.run_child_window(dialog);
```
*But* that would block the caller; we need an async solution. Perhaps it would be possible to use futures (i.e. just make that an `async` method); I haven't investigated yet.

Currently the only way windows can communicate is via global memory (as in the `sync-counter` example) or via shared channels. The message box is able to examine its own state on closure via [`add_callback`](https://docs.rs/kas/0.5.0/kas/widget/struct.Window.html#method.add_callback). This will let you do what you want, but it's not a nice way to write a GUI.

Regarding the crash, I can't tell from that backtrace. Could you try copying the whole backtrace (e.g. by running from a terminal)? There are definitely problems regarding closing multiple windows; I get a hang in `destroy_swapchain_khr` (`ash-0.31.0/src/vk/extensions.rs:612`).

**Comment by codec-abc** [comment]
Thanks for the detail. I need to take another look into popup. One thing that I don't understand is how to notify the parent Window. I understand that using something like ``Rc<RefCell<T>>`` I can shared data between the parent and child window. I can also use the ``add_callback`` so the child can know when it is closing. But how about the parent? Since Rust make it  difficult to have reference from child to parent it not obvious to me what to use here.

Regarding the crash I don't have more data to give. I am already running my program from the terminal and didn't get more info than that. If I set up a repository that contains the behavior (at least on my computer woulrd that help you tracking the bug down? Also, since the bug is not deterministic it is probably a bug in unsafe code (or in the compiler but it seems less likely to be so), it might not be in KAS. Does KAS contains unsafe code?

**Comment by dhardy** [comment]
To update the parent, use a shared [update handle](https://docs.rs/kas/0.5.0/kas/event/struct.Manager.html#method.update_on_handle) between the parent and popup.

Eh, yes KAS contains some unsafe code, but more so the whole rendering stack is "unsafe", from graphics drivers, Vulkan library, and all the way up to wgpu which is a (mostly) safe wrapper around Vulkan/DX12/Metal. That would be my first guess. But then there's also winit which is a wrapper around various system APIs. Basically none of this has Rust's usual memory-safety guarantees, unfortunately. I opened https://github.com/gfx-rs/wgpu-rs/issues/584 to report the issue I mentioned, but there's only a small chance it's related to your crash. There isn't a lot to go on in your screenshot.

**Comment by codec-abc** [comment]
Thanks again! I think I can work my way around the Window API now. The problem that remains is the crash. It happens even on the gallery example for me. If I compile and run the example (of the master branch) and then open and close the child window it might crash (bug is not deterministic for some reason). The probability of crash to happen on close seems to be pretty high (like 1/2 or 1/3). Do you get the same behavior or is it something that only happen on my computer? Also, is there anything I can do to help pin down this bug (whether it happen in KAS, winit or somewhere else? If you know some commands that can, for example, produce useful dumps don't hesitate to tell me. My unsafe debugging are rather poor.

**Comment by dhardy** [comment]
@codec-abc see [Debugging wgpu Applications](https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications).

**Comment by dhardy** [comment]
If you don't mind, I'm going to close this issue since the original question was answered and the crash report contains insufficient information to act on and is a separate issue anyway. If you can provide more information on the crash please open a new issue.

**Comment by dhardy** [comment]
For anyone reading this later, #130 introduces a special `Future` and `Window::on_drop` method to make returning values from child windows easier.
