### ISSUE TITLE
Examples not compiling

### ISSUE THREAD

**Issue by ssmid** [kas-gui/kas#181]
I tried to follow the quick start guide, but tests and compiling failed:

```
$ cargo test
[...]
   Compiling kas v0.6.0
error[E0391]: cycle detected when computing the bounds for type parameter `V`
  --> src/widget/view/single_view.rs:31:15
   |
31 |     V: Driver<T::Item> = driver::Default,
   |               ^^^^^^^
   |
note: ...which requires computing the bounds for type parameter `T`...
  --> src/widget/view/single_view.rs:30:38
   |
30 |     T: SingleData + UpdatableAll<(), V::Msg> + 'static,
   |                                      ^^^^^^
   = note: ...which again requires computing the bounds for type parameter `V`, completing the cycle
note: cycle used when computing the bounds for type parameter `V`
  --> src/widget/view/single_view.rs:31:5
   |
31 |     V: Driver<T::Item> = driver::Default,
   |     ^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0391`.
error: could not compile `kas`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...

[same error once more, same lines]

error: build failed
```

I was wondering, because the GitHub CI says all checks passed on the current commit.

Edit: Linux Mint, dependencies installed, quickstart performed line by line, creating a new crate with the contents of the hello example worked just fine (kas from crates.io), so its probably a not yet released commit

**Comment by dhardy** [comment]
I actually noticed this yesterday... it turns out that the nightly and beta compilers can deal with this partial cycle (it's not really a cycle since e.g. `V::Msg` can be extracted as its own parameter).

Rather than work around it I think it's best just to recommend use of Rust 1.52.0 (beta). (I will try not to depend on beta compilers in the future.)

**Comment by dhardy** [comment]
See #179. I'll let you close or ask here if you have more problems.

**Comment by ssmid** [comment]
The beta compiler made my laptop unresponsive and CLion crash, but in the end it worked like a charm. Thank you :)

**Comment by dhardy** [comment]
Ugh! You have enough RAM? If not using `-j` to limit the number of build jobs may help.

**Comment by ssmid** [comment]
Seems like it has been the CPU load. I never had this before with the stable toolchain... But a job limit should do the trick. Impressive project by the way, given the number of contributers, so far.
