### ISSUE TITLE
Keyboard navigation is unintuitive

### ISSUE THREAD

**Issue by Aloso** [kas-gui/kas#231]
If I don't know which shortcuts I have to press (e.g. <kbd>Esc</kbd> to move focus away from a text input), this GUI framework is not usable with a keyboard. Please make sure it behaves the same as other GUI frameworks, so it can be used without reading a manual.

Here are some things I expect from a GUI:

* When a text input is focused, <kbd>Tab</kbd> focuses the next widget and <kbd>Shift+Tab</kbd> focuses the previous widget. There should not be the need to press <kbd>Esc</kbd>
* When pressing <kbd>Tab</kbd> and there is no next widget, focus the first widget. Pressing <kbd>Shift+Tab</kbd> when there is no previous widget focuses the last widget.
* Clicking (or pressing the left mouse button down) on a widget focuses the widget
* Activating a widget with a keyboard shortcut (e.g. <kbd>Alt+1</kbd> in the gallery) focuses the widget
* The menu bar usually isn't part of the tab order, it can only be focused with <kbd>Alt+...</kbd>
* When opening a menu in the menu bar and closing it again, focus is returned to the previously focused widget
* Pressing <kbd>Esc</kbd> doesn't remove focus from the active widget

Please consider adopting this behaviour.

**Comment by dhardy** [comment]
Great feedback!

> When a text input is focused, <kbd>Tab</kbd> focuses the next widget ...

This precludes being able to insert tab stops... except where specially handled (e.g. a text editor), thus leading to surprisingly different behaviour there. But sure, existing tools are this way for a reason.

> Clicking (or pressing the left mouse button down) on a widget focuses the widget

This conflicts with the design goal of not making multiple input methods (keyboard, mouse, touch) interfere with one another — though probably that goal is mis-guided.

What if no widget is yet focused — should it set focus?

**Comment by Aloso** [comment]
> What if no widget is yet focused — should it set focus?

Yes; I believe that's what browsers and other toolkits do.

**Comment by dhardy** [comment]
> Clicking (or pressing the left mouse button down) on a widget focuses the widget

What about touchscreen input? The problem here is that one can potentially touch multiple controls at once, potentially even from multiple users. But, I guess for consistency it makes sense to set nav focus on touch input too, and can't really see any problems (other than simultaneous keyboard and touchscreen input, which doesn't usually happen).

**Comment by dhardy** [comment]
@Aloso this should all be done. Would you like to test? There are a lot of finicky details so I may have missed some.

**Comment by Aloso** [comment]
@dhardy thanks for working on this! I now tried it with the latest commits. Almost all my concerns have been addressed!

Here are the remaining issues I identified:

* When clicking somewhere _outside_ of focusable widgets, the previously focused widget loses focus. Most other GUIs don't lose the focus in that situation (the exception being websites).
* When clicking on a menu item and then moving the cursor to the right side of the menu bar, the menu is closed:
  ![kas-menubar-bug](https://user-images.githubusercontent.com/15658558/128632145-5bef6f99-c700-48b4-95cb-d9fc5b682c56.gif)

* When opening a menu item with the keyboard, <kbd>Esc</kbd> restores focus to the previously focused widget. However, if the menu item is opened and/or closed by clicking on it, the focus isn't restored afterwards.

**Comment by dhardy** [comment]
Thanks for the additional reports; these should be addressed by #236.

One thing I'm not quite sure what to do about: focus regarding the `ScrollLabel`. It is not a `key_nav` widget so cannot receive focus via the keyboard, but does take *selection focus* when text is selected, which updates key-navigation focus (to point to itself — though not visually represented, it means that the next Tab widget will be the one after the scroll-label). The next PR makes it only take focus when selecting, not when clicking or deselecting. Is this appropriate?

Another slight oddity is making sure commands like Ctrl+C and Escape affect selected text even though another widget may have navigation focus. I *think* I got this right. Curiously a `ScrollLabel` supports Ctrl+A to select all text, but only when it has navigation focus.

**Comment by dhardy** [comment]
I believe all issues are fixed.
