### ISSUE TITLE
Menus slow to open

### ISSUE THREAD

**Issue by nyanpasu64** [kas-gui/kas#251]
When I run `cargo run --example gallery` (or `--release`), and click on a menu, it takes a noticeable delay before the menu opens. Moving the mouse to switch menus is instant. And randomly I get a menu which is instant to open.

I took a perf capture ([link](https://github.com/kas-gui/kas/files/7249612/slow.menu.open.perf.tar.gz)) of me repeatedly clicking the menu bar to open a menu, using `perf record --call-graph dwarf -p (pgrep gallery)`. (`--call-graph fp` didn't work, and having `perf` profile process startup polluted the results.) However I don't know what's wrong in this capture; it seems kas is mostly doing work in wgpu, some involving scrollbars.

Operating System: Arch Linux
KDE Plasma Version: 5.22.90
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.14.7-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GT 730/PCIe/SSE2

**Comment by dhardy** [comment]
Delays on opening menus in *some* cases is deliberate; without that navigating submenus can be a pain (try hovering over a submenu title to open it, then moving directly to an entry but diagonally across another item in the parent menu). This behaviour is used by Qt. However it's entirely possible that the logic in KAS is not quite correct.

In case it helps with testing, the delay is configurable (see [config files](https://github.com/kas-gui/kas/#config-files) and set `menu_delay_ns` in the main config file).

**Comment by nyanpasu64** [comment]
Opening menubar items is instant on click on Windows and Linux, and opening right-click menus (I didn't test) is instant on click on Linux, and instant on release on Windows. I think the delay should only apply to sub-menus activated by hover, not top-level menus activated by click (the delay does apply to them now).

**Comment by dhardy** [comment]
> I think the delay should only apply to sub-menus activated by hover, not top-level menus activated by click

Agreed; this should be fixed (easy enough to fix though slightly annoying since there isn't a clean code separation between top-level and sub-menus).

**Comment by nyanpasu64** [comment]
(Also what editor do you use? In vscode, rust-analyzer keeps crashing on every keystroke, in any example app with a `make_widget! { impl {` block. (https://github.com/rust-analyzer/rust-analyzer/issues/10386))

**Comment by dhardy** [comment]
Huh, that's good to know!

I use `kate`, sometimes with the LSP plugin (for rust analyzer) but mostly only with syntax-highlighting and standard indentation stuff. I don't actually find the extra code navigation tools or in-editor error reporting to be that useful.
