### ISSUE TITLE
reproducible panic in SizeRules::solve_seq_total

### ISSUE THREAD

**Issue by captchaKing** [kas-gui/kas#273]
Steps to reproduce:
- open kas/examples/data-list.rs
- change line 140: `let list = IndexedList::new_with_direction(Direction::Down, entries);`
to `let list = IndexedList::new_with_direction(Direction::Right, entries);`
- start example with `cargo run --example data-list`
- set Number of rows to 100
- see the panic message: `thread 'main' panicked at 'assertion failed: out.iter().all(|w| *w >= 0)', ~/workspace/kas/crates/kas-core/src/layout/size_rules.rs:417:13`

**Comment by dhardy** [comment]
Fixed in f138d128.

The vertical layout is still broken in this case (presumably at some stage it thinks line-wrapping is necessary, hence the excess vertical space) but I'll leave that for now.
