### ISSUE TITLE
Menu behaviour

### ISSUE THREAD

**Issue by captchaKing** [kas-gui/kas#278]
I made some changes on my fork. May i PR for any of this or all of them?

1. Menu-items double highlighting (TkAction::REDRAW somehow not passed) 
https://user-images.githubusercontent.com/63655582/152634186-d4aeab5d-cc59-44bd-9066-10e9e8c8b82a.mp4
2. Grabbing bug
https://user-images.githubusercontent.com/63655582/152634346-4731ccc3-f61a-4912-9043-d6226d198ea3.mp4
3. Minor annoyance - when grabbing ends out of menu-item, menu closes (and that's how it's done in QT and GTK, but not in Chrome or Firefox):
https://user-images.githubusercontent.com/63655582/152634649-93ea3e96-e77f-4617-932a-b3be937c7baf.mp4
But consider user doing it fast, he may think that click actually happened on menu-item and something changed in the app.
4. Inactive delayed-menu's item
https://user-images.githubusercontent.com/63655582/152655399-e887b92e-910a-49d1-a792-8253a2579f7d.mp4
5. Menubar's root item sometimes suddenly reopens on close
https://user-images.githubusercontent.com/63655582/152655615-f60da48e-8543-4126-a100-169ba88a6882.mp4

**Comment by captchaKing** [comment]
4. Inactive delayed-menu's item
https://user-images.githubusercontent.com/63655582/152655399-e887b92e-910a-49d1-a792-8253a2579f7d.mp4
5. Menubar's root item sometimes suddenly reopens on close
https://user-images.githubusercontent.com/63655582/152655615-f60da48e-8543-4126-a100-169ba88a6882.mp4

**Comment by dhardy** [comment]
Sure, a PR is welcome.

Point 3 was deliberate (I mostly copied Qt behaviour), but you are right that it's not optimal.

Otherwise they just sound like bugs. I've had enough bugs with menu logic that I don't know if a better approach is needed.
