### ISSUE TITLE
panic on Intel HD 520 (Mailbox)

### ISSUE THREAD

**Issue by Zhou-Pixel** [kas-gui/kas#368]
I can't run any example from source.
system:EndeavourOS(base on arch)
kde plasma version: 5.26.4
x11/wayland:x11
cpu:i3-6006u
gpu:intel hd 520
output:
thread 'main' panicked at 'Error in Surface::configure: requested present mode Mailbox is not in the list of supported present modes: [Fifo]', /home/zhou/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/wgpu-0.14.2/src/backend/direct.rs:274:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by dhardy** [comment]
It's not KDE, it's WGPU on older Intel graphics hardware. Please try [wgpu](https://github.com/gfx-rs/wgpu/) examples and see what works.

**Comment by dhardy** [comment]
You can also try changing the `present_mode` to `Fifo` in `crates/kas-wgpu/src/window.rs:141`. No other change required.

**Comment by Zhou-Pixel** [comment]
> 
It has the same problem on another computer that only has a different processor(CPU:AMD R5-5600H).

I tried some wgpu examples like https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples/water, it works fine. 
output:
Using Mesa Intel(R) HD Graphics 520 (SKL GT2) (Gl)
Avg frame time 15.864518ms
Avg frame time 16.645708ms
Avg frame time 16.64359ms
Avg frame time 16.645853ms
Avg frame time 16.645884ms
Avg frame time 16.645628ms
Avg frame time 16.643642ms

**Comment by Zhou-Pixel** [comment]
> You can also try changing the `present_mode` to `Fifo` in `crates/kas-wgpu/src/window.rs:141`. No other change required.

It works fine with changing the `present_mode` to `Fifo`.
