### ISSUE TITLE
mdbook for kas

### ISSUE THREAD

**Issue by mateolafalce** [kas-gui/kas#394]
Hi, it's been a few weeks since I started using kas-gui and I think it's awesome. The great project is growing, and I believe it would be a good idea to systematically document the project. I have experience doing that kind of thing, and it would be a pleasure to work with you!

**Comment by dhardy** [comment]
Hi, thanks for the feedback.

What sort of documentation are you talking about? There are already these in separate repos:

- [Tutorials](https://github.com/kas-gui/tutorials): only covers the basics so far and will need a complete re-write after the next release
- [Design](https://github.com/kas-gui/design) recently added in the style of Rust's RFCs; doesn't contain much yet. I have a pile of informal notes locally but many are outdated/redundant/incomplete so I can't just dump them here.
- [Blog](https://github.com/kas-gui/blog): the occasional design post; I have at least one in progress (tied to the current change set, aka Input Data)

**Comment by mateolafalce** [comment]
I was referring to something like the [blog](https://github.com/kas-gui/blog) you have, I was unaware of it, sorry
